"""sayt jadvallari

Revision ID: 7d265740df9b
Revises: 
Create Date: 2026-09-14 02:20:42.730245
"""
from alembic import op
import sqlalchemy as sa


revision = '7d265740df9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advantage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=4), server_default='', nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advantage_created_at'), 'advantage', ['created_at'], unique=False)
    op.create_index(op.f('ix_advantage_is_published'), 'advantage', ['is_published'], unique=False)
    op.create_index(op.f('ix_advantage_order'), 'advantage', ['order'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('name_ru', sa.String(length=160), server_default='', nullable=False),
    sa.Column('name_uz', sa.String(length=160), server_default='', nullable=False),
    sa.Column('name_en', sa.String(length=160), server_default='', nullable=False),
    sa.Column('address_ru', sa.String(length=300), server_default='', nullable=False),
    sa.Column('address_uz', sa.String(length=300), server_default='', nullable=False),
    sa.Column('address_en', sa.String(length=300), server_default='', nullable=False),
    sa.Column('landmark_ru', sa.String(length=300), server_default='', nullable=False),
    sa.Column('landmark_uz', sa.String(length=300), server_default='', nullable=False),
    sa.Column('landmark_en', sa.String(length=300), server_default='', nullable=False),
    sa.Column('working_hours_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('working_hours_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('working_hours_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=32), server_default='', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('map_url_yandex', sa.String(length=500), server_default='', nullable=False),
    sa.Column('map_url_google', sa.String(length=500), server_default='', nullable=False),
    sa.Column('cover', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_branch_company_id'), 'branch', ['company_id'], unique=False)
    op.create_index(op.f('ix_branch_created_at'), 'branch', ['created_at'], unique=False)
    op.create_index(op.f('ix_branch_is_published'), 'branch', ['is_published'], unique=False)
    op.create_index(op.f('ix_branch_order'), 'branch', ['order'], unique=False)
    op.create_table('child_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon_name', sa.String(length=16), server_default='brain', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_skill_created_at'), 'child_skill', ['created_at'], unique=False)
    op.create_index(op.f('ix_child_skill_is_published'), 'child_skill', ['is_published'], unique=False)
    op.create_index(op.f('ix_child_skill_order'), 'child_skill', ['order'], unique=False)
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_direction_created_at'), 'direction', ['created_at'], unique=False)
    op.create_index(op.f('ix_direction_is_published'), 'direction', ['is_published'], unique=False)
    op.create_index(op.f('ix_direction_order'), 'direction', ['order'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_ru', sa.String(length=255), server_default='', nullable=False),
    sa.Column('question_uz', sa.String(length=255), server_default='', nullable=False),
    sa.Column('question_en', sa.String(length=255), server_default='', nullable=False),
    sa.Column('answer_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_en', sa.Text(), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_created_at'), 'faq', ['created_at'], unique=False)
    op.create_index(op.f('ix_faq_is_published'), 'faq', ['is_published'], unique=False)
    op.create_index(op.f('ix_faq_order'), 'faq', ['order'], unique=False)
    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('photo', sa.String(length=300), server_default='', nullable=False),
    sa.Column('position_ru', sa.String(length=160), server_default='', nullable=False),
    sa.Column('position_uz', sa.String(length=160), server_default='', nullable=False),
    sa.Column('position_en', sa.String(length=160), server_default='', nullable=False),
    sa.Column('bio_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('bio_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('bio_en', sa.Text(), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founder_created_at'), 'founder', ['created_at'], unique=False)
    op.create_index(op.f('ix_founder_is_published'), 'founder', ['is_published'], unique=False)
    op.create_index(op.f('ix_founder_order'), 'founder', ['order'], unique=False)
    op.create_table('future_benefit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_benefit_created_at'), 'future_benefit', ['created_at'], unique=False)
    op.create_index(op.f('ix_future_benefit_is_published'), 'future_benefit', ['is_published'], unique=False)
    op.create_index(op.f('ix_future_benefit_order'), 'future_benefit', ['order'], unique=False)
    op.create_table('news_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_news_category_created_at'), 'news_category', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_category_is_published'), 'news_category', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_category_order'), 'news_category', ['order'], unique=False)
    op.create_table('page_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('eyebrow_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('eyebrow_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('eyebrow_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('title_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('title_en', sa.Text(), server_default='', nullable=False),
    sa.Column('subtitle_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('subtitle_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('subtitle_en', sa.Text(), server_default='', nullable=False),
    sa.Column('text_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('text_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('text_en', sa.Text(), server_default='', nullable=False),
    sa.Column('note_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('note_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('note_en', sa.Text(), server_default='', nullable=False),
    sa.Column('button_label_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button_label_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button_label_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('button2_label_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button2_label_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button2_label_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('button2_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('image2', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_page_section_order'), 'page_section', ['order'], unique=False)
    op.create_index(op.f('ix_page_section_page'), 'page_section', ['page'], unique=False)
    op.create_table('parent_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('relation_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('relation_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('relation_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('photo', sa.String(length=300), server_default='', nullable=False),
    sa.Column('video_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('text_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('text_en', sa.Text(), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_review_created_at'), 'parent_review', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_review_is_published'), 'parent_review', ['is_published'], unique=False)
    op.create_index(op.f('ix_parent_review_order'), 'parent_review', ['order'], unique=False)
    op.create_table('project_defence_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_ru', sa.String(length=32), server_default='', nullable=False),
    sa.Column('label_uz', sa.String(length=32), server_default='', nullable=False),
    sa.Column('label_en', sa.String(length=32), server_default='', nullable=False),
    sa.Column('icon_name', sa.String(length=16), server_default='calendar', nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_defence_step_created_at'), 'project_defence_step', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_defence_step_is_published'), 'project_defence_step', ['is_published'], unique=False)
    op.create_index(op.f('ix_project_defence_step_order'), 'project_defence_step', ['order'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('questions_per_attempt', sa.SmallInteger(), server_default='20', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_quiz_created_at'), 'quiz', ['created_at'], unique=False)
    op.create_index(op.f('ix_quiz_is_published'), 'quiz', ['is_published'], unique=False)
    op.create_index(op.f('ix_quiz_order'), 'quiz', ['order'], unique=False)
    op.create_table('school_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_feature_created_at'), 'school_feature', ['created_at'], unique=False)
    op.create_index(op.f('ix_school_feature_is_published'), 'school_feature', ['is_published'], unique=False)
    op.create_index(op.f('ix_school_feature_order'), 'school_feature', ['order'], unique=False)
    op.create_table('site_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), server_default='', nullable=False),
    sa.Column('extra_phone', sa.String(length=32), server_default='', nullable=False),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('work_hours_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('work_hours_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('work_hours_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('telegram_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('instagram_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('youtube_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('facebook_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('space_app_ios_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('space_app_android_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('privacy_policy_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('offer_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('promo_video_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('promo_video', sa.String(length=300), server_default='', nullable=False),
    sa.Column('promo_cover', sa.String(length=300), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('space_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('screenshot', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_feature_created_at'), 'space_feature', ['created_at'], unique=False)
    op.create_index(op.f('ix_space_feature_is_published'), 'space_feature', ['is_published'], unique=False)
    op.create_index(op.f('ix_space_feature_order'), 'space_feature', ['order'], unique=False)
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), server_default='', nullable=False),
    sa.Column('label_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('label_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('label_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_created_at'), 'statistic', ['created_at'], unique=False)
    op.create_index(op.f('ix_statistic_is_published'), 'statistic', ['is_published'], unique=False)
    op.create_index(op.f('ix_statistic_order'), 'statistic', ['order'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lms_teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('photo', sa.String(length=300), server_default='', nullable=False),
    sa.Column('position_ru', sa.String(length=160), server_default='', nullable=False),
    sa.Column('position_uz', sa.String(length=160), server_default='', nullable=False),
    sa.Column('position_en', sa.String(length=160), server_default='', nullable=False),
    sa.Column('badge', sa.String(length=60), server_default='', nullable=False),
    sa.Column('bio_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('bio_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('bio_en', sa.Text(), server_default='', nullable=False),
    sa.Column('company', sa.String(length=120), server_default='', nullable=False),
    sa.Column('company_logo', sa.String(length=300), server_default='', nullable=False),
    sa.Column('experience_years', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('students_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('telegram_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('linkedin_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('instagram_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_teacher_created_at'), 'teacher', ['created_at'], unique=False)
    op.create_index(op.f('ix_teacher_is_published'), 'teacher', ['is_published'], unique=False)
    op.create_index(op.f('ix_teacher_lms_teacher_id'), 'teacher', ['lms_teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_order'), 'teacher', ['order'], unique=False)
    op.create_table('branch_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_image_branch_id'), 'branch_image', ['branch_id'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=160), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=160), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=160), server_default='', nullable=False),
    sa.Column('subtitle_ru', sa.String(length=300), server_default='', nullable=False),
    sa.Column('subtitle_uz', sa.String(length=300), server_default='', nullable=False),
    sa.Column('subtitle_en', sa.String(length=300), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('card_image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('hero_image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('accent_color', sa.String(length=7), server_default='#FF5A1F', nullable=False),
    sa.Column('age_from', sa.SmallInteger(), server_default='7', nullable=False),
    sa.Column('age_to', sa.SmallInteger(), server_default='17', nullable=False),
    sa.Column('duration_months', sa.SmallInteger(), server_default='9', nullable=False),
    sa.Column('lessons_per_week', sa.SmallInteger(), server_default='2', nullable=False),
    sa.Column('lesson_duration_minutes', sa.SmallInteger(), server_default='90', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_course_created_at'), 'course', ['created_at'], unique=False)
    op.create_index(op.f('ix_course_direction_id'), 'course', ['direction_id'], unique=False)
    op.create_index(op.f('ix_course_is_featured'), 'course', ['is_featured'], unique=False)
    op.create_index(op.f('ix_course_is_published'), 'course', ['is_published'], unique=False)
    op.create_index(op.f('ix_course_order'), 'course', ['order'], unique=False)
    op.create_index(op.f('ix_course_program_id'), 'course', ['program_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=255), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=255), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=255), server_default='', nullable=False),
    sa.Column('excerpt_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('excerpt_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('excerpt_en', sa.Text(), server_default='', nullable=False),
    sa.Column('body_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('body_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('body_en', sa.Text(), server_default='', nullable=False),
    sa.Column('cover', sa.String(length=300), server_default='', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reading_minutes', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_news_category_id'), 'news', ['category_id'], unique=False)
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_is_featured'), 'news', ['is_featured'], unique=False)
    op.create_index(op.f('ix_news_is_published'), 'news', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_order'), 'news', ['order'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_created_at'), 'outcome', ['created_at'], unique=False)
    op.create_index(op.f('ix_outcome_quiz_id'), 'outcome', ['quiz_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('text_ru', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text_uz', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text_en', sa.String(length=300), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_created_at'), 'question', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('section_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('value_ru', sa.String(length=120), server_default='', nullable=False),
    sa.Column('value_uz', sa.String(length=120), server_default='', nullable=False),
    sa.Column('value_en', sa.String(length=120), server_default='', nullable=False),
    sa.Column('label_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('label_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('label_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('title_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('title_en', sa.Text(), server_default='', nullable=False),
    sa.Column('text_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('text_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('text_en', sa.Text(), server_default='', nullable=False),
    sa.Column('note_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('note_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('note_en', sa.Text(), server_default='', nullable=False),
    sa.Column('list_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('list_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('list_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon_name', sa.String(length=60), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['page_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_item_section_id'), 'section_item', ['section_id'], unique=False)
    op.create_table('teacher_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'skill_id')
    )
    op.create_index(op.f('ix_teacher_skill_skill_id'), 'teacher_skill', ['skill_id'], unique=False)
    op.create_index(op.f('ix_teacher_skill_teacher_id'), 'teacher_skill', ['teacher_id'], unique=False)
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lms_vacancy_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('requirements_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('requirements_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('requirements_en', sa.Text(), server_default='', nullable=False),
    sa.Column('conditions_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('conditions_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('conditions_en', sa.Text(), server_default='', nullable=False),
    sa.Column('employment_type', sa.String(length=16), server_default='full_time', nullable=False),
    sa.Column('icon_name', sa.String(length=16), server_default='code', nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), server_default='UZS', nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_vacancy_branch_id'), 'vacancy', ['branch_id'], unique=False)
    op.create_index(op.f('ix_vacancy_created_at'), 'vacancy', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_is_open'), 'vacancy', ['is_open'], unique=False)
    op.create_index(op.f('ix_vacancy_is_published'), 'vacancy', ['is_published'], unique=False)
    op.create_index(op.f('ix_vacancy_lms_vacancy_id'), 'vacancy', ['lms_vacancy_id'], unique=False)
    op.create_index(op.f('ix_vacancy_order'), 'vacancy', ['order'], unique=False)
    op.create_table('course_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('question_ru', sa.String(length=255), server_default='', nullable=False),
    sa.Column('question_uz', sa.String(length=255), server_default='', nullable=False),
    sa.Column('question_en', sa.String(length=255), server_default='', nullable=False),
    sa.Column('answer_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_en', sa.Text(), server_default='', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_faq_course_id'), 'course_faq', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_faq_created_at'), 'course_faq', ['created_at'], unique=False)
    op.create_table('course_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=300), server_default='', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_feature_course_id'), 'course_feature', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_feature_created_at'), 'course_feature', ['created_at'], unique=False)
    op.create_table('course_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('title_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('title_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description_ru', sa.Text(), server_default='', nullable=False),
    sa.Column('description_uz', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('duration_months', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_stage_course_id'), 'course_stage', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_stage_created_at'), 'course_stage', ['created_at'], unique=False)
    op.create_table('course_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'teacher_id')
    )
    op.create_index(op.f('ix_course_teacher_course_id'), 'course_teacher', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_teacher_teacher_id'), 'course_teacher', ['teacher_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=13), server_default='', nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('child_age', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='home', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('admin_note', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_created_at'), 'lead', ['created_at'], unique=False)
    op.create_index('ix_lead_status_created', 'lead', ['status', 'created_at'], unique=False)
    op.create_table('news_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=300), server_default='', nullable=False),
    sa.Column('caption_ru', sa.String(length=200), server_default='', nullable=False),
    sa.Column('caption_uz', sa.String(length=200), server_default='', nullable=False),
    sa.Column('caption_en', sa.String(length=200), server_default='', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_image_news_id'), 'news_image', ['news_id'], unique=False)
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('text_ru', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text_uz', sa.String(length=300), server_default='', nullable=False),
    sa.Column('text_en', sa.String(length=300), server_default='', nullable=False),
    sa.Column('skill', sa.String(length=32), server_default='', nullable=False),
    sa.Column('weight', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_created_at'), 'option', ['created_at'], unique=False)
    op.create_index(op.f('ix_option_outcome_id'), 'option', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_option_question_id'), 'option', ['question_id'], unique=False)
    op.create_table('outcome_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outcome_id', 'course_id')
    )
    op.create_index(op.f('ix_outcome_course_course_id'), 'outcome_course', ['course_id'], unique=False)
    op.create_index(op.f('ix_outcome_course_outcome_id'), 'outcome_course', ['outcome_id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=13), server_default='', nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_index(op.f('ix_submission_created_at'), 'submission', ['created_at'], unique=False)
    op.create_index(op.f('ix_submission_quiz_id'), 'submission', ['quiz_id'], unique=False)
    op.create_table('vacancy_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=13), server_default='', nullable=False),
    sa.Column('email', sa.String(length=254), server_default='', nullable=False),
    sa.Column('cover_letter', sa.Text(), server_default='', nullable=False),
    sa.Column('resume', sa.String(length=300), server_default='', nullable=False),
    sa.Column('resume_url', sa.String(length=300), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_application_created_at'), 'vacancy_application', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_application_status'), 'vacancy_application', ['status'], unique=False)
    op.create_index(op.f('ix_vacancy_application_vacancy_id'), 'vacancy_application', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_application_vacancy_id'), table_name='vacancy_application')
    op.drop_index(op.f('ix_vacancy_application_status'), table_name='vacancy_application')
    op.drop_index(op.f('ix_vacancy_application_created_at'), table_name='vacancy_application')
    op.drop_table('vacancy_application')
    op.drop_index(op.f('ix_submission_quiz_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_created_at'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_outcome_course_outcome_id'), table_name='outcome_course')
    op.drop_index(op.f('ix_outcome_course_course_id'), table_name='outcome_course')
    op.drop_table('outcome_course')
    op.drop_index(op.f('ix_option_question_id'), table_name='option')
    op.drop_index(op.f('ix_option_outcome_id'), table_name='option')
    op.drop_index(op.f('ix_option_created_at'), table_name='option')
    op.drop_table('option')
    op.drop_index(op.f('ix_news_image_news_id'), table_name='news_image')
    op.drop_table('news_image')
    op.drop_index('ix_lead_status_created', table_name='lead')
    op.drop_index(op.f('ix_lead_created_at'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_course_teacher_teacher_id'), table_name='course_teacher')
    op.drop_index(op.f('ix_course_teacher_course_id'), table_name='course_teacher')
    op.drop_table('course_teacher')
    op.drop_index(op.f('ix_course_stage_created_at'), table_name='course_stage')
    op.drop_index(op.f('ix_course_stage_course_id'), table_name='course_stage')
    op.drop_table('course_stage')
    op.drop_index(op.f('ix_course_feature_created_at'), table_name='course_feature')
    op.drop_index(op.f('ix_course_feature_course_id'), table_name='course_feature')
    op.drop_table('course_feature')
    op.drop_index(op.f('ix_course_faq_created_at'), table_name='course_faq')
    op.drop_index(op.f('ix_course_faq_course_id'), table_name='course_faq')
    op.drop_table('course_faq')
    op.drop_index(op.f('ix_vacancy_order'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_lms_vacancy_id'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_is_published'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_is_open'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_created_at'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_branch_id'), table_name='vacancy')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_teacher_skill_teacher_id'), table_name='teacher_skill')
    op.drop_index(op.f('ix_teacher_skill_skill_id'), table_name='teacher_skill')
    op.drop_table('teacher_skill')
    op.drop_index(op.f('ix_section_item_section_id'), table_name='section_item')
    op.drop_table('section_item')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_index(op.f('ix_question_created_at'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_outcome_quiz_id'), table_name='outcome')
    op.drop_index(op.f('ix_outcome_created_at'), table_name='outcome')
    op.drop_table('outcome')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_order'), table_name='news')
    op.drop_index(op.f('ix_news_is_published'), table_name='news')
    op.drop_index(op.f('ix_news_is_featured'), table_name='news')
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.drop_index(op.f('ix_news_category_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_course_program_id'), table_name='course')
    op.drop_index(op.f('ix_course_order'), table_name='course')
    op.drop_index(op.f('ix_course_is_published'), table_name='course')
    op.drop_index(op.f('ix_course_is_featured'), table_name='course')
    op.drop_index(op.f('ix_course_direction_id'), table_name='course')
    op.drop_index(op.f('ix_course_created_at'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_branch_image_branch_id'), table_name='branch_image')
    op.drop_table('branch_image')
    op.drop_index(op.f('ix_teacher_order'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_lms_teacher_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_is_published'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_created_at'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_statistic_order'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_is_published'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_created_at'), table_name='statistic')
    op.drop_table('statistic')
    op.drop_index(op.f('ix_space_feature_order'), table_name='space_feature')
    op.drop_index(op.f('ix_space_feature_is_published'), table_name='space_feature')
    op.drop_index(op.f('ix_space_feature_created_at'), table_name='space_feature')
    op.drop_table('space_feature')
    op.drop_table('skill')
    op.drop_table('site_settings')
    op.drop_table('site_revision')
    op.drop_index(op.f('ix_school_feature_order'), table_name='school_feature')
    op.drop_index(op.f('ix_school_feature_is_published'), table_name='school_feature')
    op.drop_index(op.f('ix_school_feature_created_at'), table_name='school_feature')
    op.drop_table('school_feature')
    op.drop_index(op.f('ix_quiz_order'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_is_published'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_created_at'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_project_defence_step_order'), table_name='project_defence_step')
    op.drop_index(op.f('ix_project_defence_step_is_published'), table_name='project_defence_step')
    op.drop_index(op.f('ix_project_defence_step_created_at'), table_name='project_defence_step')
    op.drop_table('project_defence_step')
    op.drop_index(op.f('ix_parent_review_order'), table_name='parent_review')
    op.drop_index(op.f('ix_parent_review_is_published'), table_name='parent_review')
    op.drop_index(op.f('ix_parent_review_created_at'), table_name='parent_review')
    op.drop_table('parent_review')
    op.drop_index(op.f('ix_page_section_page'), table_name='page_section')
    op.drop_index(op.f('ix_page_section_order'), table_name='page_section')
    op.drop_table('page_section')
    op.drop_index(op.f('ix_news_category_order'), table_name='news_category')
    op.drop_index(op.f('ix_news_category_is_published'), table_name='news_category')
    op.drop_index(op.f('ix_news_category_created_at'), table_name='news_category')
    op.drop_table('news_category')
    op.drop_index(op.f('ix_future_benefit_order'), table_name='future_benefit')
    op.drop_index(op.f('ix_future_benefit_is_published'), table_name='future_benefit')
    op.drop_index(op.f('ix_future_benefit_created_at'), table_name='future_benefit')
    op.drop_table('future_benefit')
    op.drop_index(op.f('ix_founder_order'), table_name='founder')
    op.drop_index(op.f('ix_founder_is_published'), table_name='founder')
    op.drop_index(op.f('ix_founder_created_at'), table_name='founder')
    op.drop_table('founder')
    op.drop_index(op.f('ix_faq_order'), table_name='faq')
    op.drop_index(op.f('ix_faq_is_published'), table_name='faq')
    op.drop_index(op.f('ix_faq_created_at'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_direction_order'), table_name='direction')
    op.drop_index(op.f('ix_direction_is_published'), table_name='direction')
    op.drop_index(op.f('ix_direction_created_at'), table_name='direction')
    op.drop_table('direction')
    op.drop_index(op.f('ix_child_skill_order'), table_name='child_skill')
    op.drop_index(op.f('ix_child_skill_is_published'), table_name='child_skill')
    op.drop_index(op.f('ix_child_skill_created_at'), table_name='child_skill')
    op.drop_table('child_skill')
    op.drop_index(op.f('ix_branch_order'), table_name='branch')
    op.drop_index(op.f('ix_branch_is_published'), table_name='branch')
    op.drop_index(op.f('ix_branch_created_at'), table_name='branch')
    op.drop_index(op.f('ix_branch_company_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_advantage_order'), table_name='advantage')
    op.drop_index(op.f('ix_advantage_is_published'), table_name='advantage')
    op.drop_index(op.f('ix_advantage_created_at'), table_name='advantage')
    op.drop_table('advantage')
    # ### end Alembic commands ###
