# Generated by Django 5.2.6 on 2026-08-29 13:42

import apps.accounts.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=160, verbose_name='lavozim (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=160, verbose_name='lavozim (uz)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='lavozim (en)')),
                ('description_ru', models.TextField(verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('requirements_ru', models.TextField(blank=True, verbose_name='talablar (ru)')),
                ('requirements_uz', models.TextField(blank=True, verbose_name='talablar (uz)')),
                ('requirements_en', models.TextField(blank=True, verbose_name='talablar (en)')),
                ('conditions_ru', models.TextField(blank=True, verbose_name='shartlar (ru)')),
                ('conditions_uz', models.TextField(blank=True, verbose_name='shartlar (uz)')),
                ('conditions_en', models.TextField(blank=True, verbose_name='shartlar (en)')),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Yarim stavka'), ('project', 'Loyiha asosida')], default='full_time', max_length=16, verbose_name='bandlik turi')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='maosh (dan)')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='maosh (gacha)')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='ochiq')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('phone', models.CharField(max_length=13, validators=[apps.accounts.validators.validate_uz_phone], verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('cover_letter', models.TextField(blank=True, max_length=2000, verbose_name='xat')),
                ('resume', models.FileField(blank=True, upload_to='resumes/%Y/%m/', verbose_name='rezyume')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', "Ko'rib chiqildi"), ('invited', 'Suhbatga taklif qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=16, verbose_name='holat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='vacancies.vacancy', verbose_name='vakansiya')),
            ],
            options={
                'verbose_name': 'Vakansiya arizasi',
                'verbose_name_plural': 'Vakansiya arizalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
