# Generated by Django 5.2.6 on 2026-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='icon_name',
            field=models.CharField(choices=[('cap', "Bitiruvchi shapkasi (o'qituvchi)"), ('badge', 'Nishon (administrator)'), ('users', 'Jamoa (kurator)'), ('headset', 'Naushnik (kol-markaz)'), ('spark', 'Uchqun (boshqa)')], default='spark', max_length=16, verbose_name='ikonka'),
        ),
    ]
