# Generated by Django 5.2.6 on 2026-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplication',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='rezyume havolasi'),
        ),
    ]
