# Generated by Django 5.2.6 on 2026-09-04 06:53

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancyapplication_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to='resumes/%Y/%m/', verbose_name='rezyume'),
        ),
    ]
