# Generated by Django 5.2.6 on 2026-09-04 07:53

import apps.core.storage
import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancyapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to=apps.core.uploads.resume_upload_to, verbose_name='rezyume'),
        ),
    ]
