# Generated by Django 5.2.17 on 2026-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancyapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(choices=[('UZS', "So'm (UZS)"), ('USD', 'Dollar ($)')], default='UZS', max_length=3, verbose_name='maosh valyutasi'),
        ),
    ]
