# Generated by Django 5.2.6 on 2026-08-29 13:42

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='rasm')),
                ('position_ru', models.CharField(max_length=160, verbose_name='lavozim (ru)')),
                ('position_uz', models.CharField(blank=True, max_length=160, verbose_name='lavozim (uz)')),
                ('position_en', models.CharField(blank=True, max_length=160, verbose_name='lavozim (en)')),
                ('bio_ru', models.TextField(blank=True, verbose_name='bio (ru)')),
                ('bio_uz', models.TextField(blank=True, verbose_name='bio (uz)')),
                ('bio_en', models.TextField(blank=True, verbose_name='bio (en)')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='ish joyi')),
                ('company_logo', models.ImageField(blank=True, upload_to='teachers/logos/', verbose_name='kompaniya logosi')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='tajriba (yil)')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
