# Generated by Django 5.2.17 on 2026-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nomi')),
                ('icon', models.ImageField(blank=True, upload_to='skills/', verbose_name='ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='rasm')),
                ('position_ru', models.CharField(max_length=160, verbose_name='lavozim (ru)')),
                ('position_uz', models.CharField(blank=True, max_length=160, verbose_name='lavozim (uz)')),
                ('position_en', models.CharField(blank=True, max_length=160, verbose_name='lavozim (en)')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='yorliq')),
                ('bio_ru', models.TextField(blank=True, verbose_name='mutaxassisligi (ru)')),
                ('bio_uz', models.TextField(blank=True, verbose_name='mutaxassisligi (uz)')),
                ('bio_en', models.TextField(blank=True, verbose_name='mutaxassisligi (en)')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='ish joyi')),
                ('company_logo', models.ImageField(blank=True, upload_to='teachers/logos/', verbose_name='kompaniya logosi')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='tajriba (yil)')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name="o'quvchilar soni")),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('skills', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.skill', verbose_name='texnologiyalar')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
