# Generated by Django 5.2.6 on 2026-08-29 14:08

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nomi')),
                ('icon', models.ImageField(blank=True, upload_to='skills/', verbose_name='ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Texnologiya',
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='badge',
            field=models.CharField(blank=True, max_length=40, verbose_name='yorliq'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name="o'quvchilar soni"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='mutaxassisligi (en)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_ru',
            field=models.TextField(blank=True, verbose_name='mutaxassisligi (ru)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_uz',
            field=models.TextField(blank=True, verbose_name='mutaxassisligi (uz)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teachers.skill', verbose_name='texnologiyalar'),
        ),
    ]
