# Generated by Django 5.2.6 on 2026-08-29 13:42

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('number', models.CharField(help_text='Masalan: 01', max_length=4, verbose_name='raqam')),
                ('title_ru', models.CharField(max_length=200, verbose_name='sarlavha (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (en)')),
                ('description_ru', models.TextField(verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('image', models.ImageField(blank=True, upload_to='advantages/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Afzallik',
                'verbose_name_plural': 'Afzalliklar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('question_ru', models.CharField(max_length=255, verbose_name='savol (ru)')),
                ('question_uz', models.CharField(blank=True, max_length=255, verbose_name='savol (uz)')),
                ('question_en', models.CharField(blank=True, max_length=255, verbose_name='savol (en)')),
                ('answer_ru', models.TextField(verbose_name='javob (ru)')),
                ('answer_uz', models.TextField(blank=True, verbose_name='javob (uz)')),
                ('answer_en', models.TextField(blank=True, verbose_name='javob (en)')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('photo', models.ImageField(blank=True, upload_to='founders/', verbose_name='rasm')),
                ('position_ru', models.CharField(max_length=160, verbose_name='lavozim (ru)')),
                ('position_uz', models.CharField(blank=True, max_length=160, verbose_name='lavozim (uz)')),
                ('position_en', models.CharField(blank=True, max_length=160, verbose_name='lavozim (en)')),
                ('bio_ru', models.TextField(blank=True, verbose_name='bio (ru)')),
                ('bio_uz', models.TextField(blank=True, verbose_name='bio (uz)')),
                ('bio_en', models.TextField(blank=True, verbose_name='bio (en)')),
            ],
            options={
                'verbose_name': 'Asoschi',
                'verbose_name_plural': 'Asoschilar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentReview',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('relation', models.CharField(blank=True, help_text='Masalan: Ali ning onasi', max_length=120, verbose_name='kim')),
                ('photo', models.ImageField(blank=True, upload_to='reviews/', verbose_name='rasm')),
                ('video_url', models.URLField(blank=True, verbose_name='video havola')),
                ('text_ru', models.TextField(verbose_name='fikr (ru)')),
                ('text_uz', models.TextField(blank=True, verbose_name='fikr (uz)')),
                ('text_en', models.TextField(blank=True, verbose_name='fikr (en)')),
            ],
            options={
                'verbose_name': 'Ota-ona fikri',
                'verbose_name_plural': 'Ota-onalar fikri',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('extra_phone', models.CharField(blank=True, max_length=32, verbose_name="qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('space_app_ios_url', models.URLField(blank=True, verbose_name='SPACE — App Store')),
                ('space_app_android_url', models.URLField(blank=True, verbose_name='SPACE — Google Play')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='Maxfiylik siyosati')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SpaceFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('title_ru', models.CharField(max_length=200, verbose_name='sarlavha (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('icon', models.ImageField(blank=True, upload_to='space/', verbose_name='ikonka')),
                ('screenshot', models.ImageField(blank=True, upload_to='space/', verbose_name='ekran rasmi')),
            ],
            options={
                'verbose_name': 'SPACE imkoniyati',
                'verbose_name_plural': 'SPACE imkoniyatlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('value', models.CharField(max_length=32, verbose_name='qiymat')),
                ('label_ru', models.CharField(max_length=120, verbose_name='izoh (ru)')),
                ('label_uz', models.CharField(blank=True, max_length=120, verbose_name='izoh (uz)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='izoh (en)')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
