# Generated by Django 5.2.6 on 2026-08-30 06:39

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_futurebenefit_projectdefencestep_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSkill',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('title_ru', models.CharField(max_length=200, verbose_name="ko'nikma (ru)")),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name="ko'nikma (uz)")),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name="ko'nikma (en)")),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('icon', models.ImageField(blank=True, upload_to='about/skills/', verbose_name='ikonka')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
