# Generated by Django 5.2.6 on 2026-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_childskill_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='childskill',
            name='icon_name',
            field=models.CharField(choices=[('brain', 'Miya (mantiq)'), ('layers', 'Qatlamlar (tizimlilik)'), ('target', 'Nishon (tahlil)'), ('cubes', 'Kublar (loyiha)'), ('chat', 'Suhbat (muloqot)'), ('spark', 'Uchqun (ijod)')], default='brain', max_length=16, verbose_name='ikonka'),
        ),
        migrations.AddField(
            model_name='projectdefencestep',
            name='icon_name',
            field=models.CharField(choices=[('calendar', 'Kalendar'), ('checklist', "Ro'yxat"), ('clock', 'Soat'), ('users', 'Ishtirokchilar')], default='calendar', max_length=16, verbose_name='ikonka'),
        ),
        migrations.AlterField(
            model_name='childskill',
            name='icon',
            field=models.ImageField(blank=True, help_text="Yuklansa, tayyor ikonka o'rniga shu rasm ko'rsatiladi", upload_to='about/skills/', verbose_name="o'z ikonkasi"),
        ),
        migrations.AlterField(
            model_name='projectdefencestep',
            name='label',
            field=models.CharField(help_text='Masalan: «1 раз», «34»', max_length=32, verbose_name='qiymat'),
        ),
        migrations.AlterField(
            model_name='projectdefencestep',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='izoh (en)'),
        ),
        migrations.AlterField(
            model_name='projectdefencestep',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='izoh (ru)'),
        ),
        migrations.AlterField(
            model_name='projectdefencestep',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='izoh (uz)'),
        ),
    ]
