# Generated by Django 5.2.6 on 2026-08-30 06:58

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_childskill_icon_name_projectdefencestep_icon_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('title_ru', models.CharField(max_length=200, verbose_name='band (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='band (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='band (en)')),
            ],
            options={
                'verbose_name': 'Maktab afzalligi',
                'verbose_name_plural': 'Maktab afzalliklari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_cover',
            field=models.ImageField(blank=True, upload_to='promo/', verbose_name='video muqovasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_url',
            field=models.URLField(blank=True, verbose_name='tanishtiruv videosi'),
        ),
    ]
