# Generated by Django 5.2.6 on 2026-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolfeature_sitesettings_promo_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours',
            field=models.CharField(blank=True, help_text='Masalan: Ежедневно с 09:00 до 20:00', max_length=120, verbose_name='ish vaqti'),
        ),
    ]
