# Generated by Django 5.2.6 on 2026-09-03 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_translate_label_relation_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video',
            field=models.FileField(blank=True, help_text='Videoni to‘g‘ridan-to‘g‘ri yuklash (mp4, webm, mov).', upload_to='promo/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogv', 'mov', 'm4v'])], verbose_name='tanishtiruv videosi — fayl'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='YouTube yoki Vimeo havolasi. Fayl yuklansa, fayl ustun turadi.', verbose_name='tanishtiruv videosi — havola'),
        ),
    ]
