# Generated by Django 5.2.6 on 2026-09-04 05:51

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_promo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRevision',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0, editable=False, verbose_name='versiya')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Kontent versiyasi',
                'verbose_name_plural': 'Kontent versiyasi',
            },
        ),
    ]
