# Generated by Django 5.2.17 on 2026-09-04 11:01

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siterevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True, verbose_name="bo'lim kaliti")),
                ('page', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='sahifa')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='tartib')),
                ('eyebrow_ru', models.CharField(blank=True, max_length=200, verbose_name='yorliq (ru)')),
                ('eyebrow_uz', models.CharField(blank=True, max_length=200, verbose_name='yorliq (uz)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=200, verbose_name='yorliq (en)')),
                ('title_ru', models.TextField(blank=True, verbose_name='sarlavha (ru)')),
                ('title_uz', models.TextField(blank=True, verbose_name='sarlavha (uz)')),
                ('title_en', models.TextField(blank=True, verbose_name='sarlavha (en)')),
                ('subtitle_ru', models.TextField(blank=True, verbose_name="qo'shimcha sarlavha (ru)")),
                ('subtitle_uz', models.TextField(blank=True, verbose_name="qo'shimcha sarlavha (uz)")),
                ('subtitle_en', models.TextField(blank=True, verbose_name="qo'shimcha sarlavha (en)")),
                ('text_ru', models.TextField(blank=True, verbose_name='matn (ru)')),
                ('text_uz', models.TextField(blank=True, verbose_name='matn (uz)')),
                ('text_en', models.TextField(blank=True, verbose_name='matn (en)')),
                ('note_ru', models.TextField(blank=True, verbose_name='eslatma (ru)')),
                ('note_uz', models.TextField(blank=True, verbose_name='eslatma (uz)')),
                ('note_en', models.TextField(blank=True, verbose_name='eslatma (en)')),
                ('button_label_ru', models.CharField(blank=True, max_length=120, verbose_name='tugma matni (ru)')),
                ('button_label_uz', models.CharField(blank=True, max_length=120, verbose_name='tugma matni (uz)')),
                ('button_label_en', models.CharField(blank=True, max_length=120, verbose_name='tugma matni (en)')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='tugma havolasi')),
                ('button2_label_ru', models.CharField(blank=True, max_length=120, verbose_name='ikkinchi tugma (ru)')),
                ('button2_label_uz', models.CharField(blank=True, max_length=120, verbose_name='ikkinchi tugma (uz)')),
                ('button2_label_en', models.CharField(blank=True, max_length=120, verbose_name='ikkinchi tugma (en)')),
                ('button2_url', models.CharField(blank=True, max_length=300, verbose_name='ikkinchi tugma havolasi')),
                ('image', models.ImageField(blank=True, upload_to='sections/', verbose_name='rasm')),
                ('image2', models.ImageField(blank=True, upload_to='sections/', verbose_name="qo'shimcha rasm")),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
            ],
            options={
                'verbose_name': "Sahifa bo'limi",
                'verbose_name_plural': "Sahifa bo'limlari",
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
            ],
            options={
                'verbose_name': "«Biz haqimizda» bo'limlari",
                'verbose_name_plural': "«Biz haqimizda» bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='CommonSection',
            fields=[
            ],
            options={
                'verbose_name': 'Umumiy bloklar (tugma, futer)',
                'verbose_name_plural': 'Umumiy bloklar (tugma, futer)',
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='ContactsSection',
            fields=[
            ],
            options={
                'verbose_name': "«Kontaktlar» sahifasi bo'limlari",
                'verbose_name_plural': "«Kontaktlar» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='CoursesSection',
            fields=[
            ],
            options={
                'verbose_name': "«Kurslar» sahifasi bo'limlari",
                'verbose_name_plural': "«Kurslar» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
            ],
            options={
                'verbose_name': "Bosh sahifa bo'limlari",
                'verbose_name_plural': "Bosh sahifa bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='ItDevSection',
            fields=[
            ],
            options={
                'verbose_name': "«IT dasturlash» sahifasi bo'limlari",
                'verbose_name_plural': "«IT dasturlash» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='ItKidsSection',
            fields=[
            ],
            options={
                'verbose_name': "«IT Kids» sahifasi bo'limlari",
                'verbose_name_plural': "«IT Kids» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='NewsPageSection',
            fields=[
            ],
            options={
                'verbose_name': "«Yangiliklar» sahifasi bo'limlari",
                'verbose_name_plural': "«Yangiliklar» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='QuizPageSection',
            fields=[
            ],
            options={
                'verbose_name': "«Test» sahifasi bo'limlari",
                'verbose_name_plural': "«Test» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='SpacePageSection',
            fields=[
            ],
            options={
                'verbose_name': "«SPACE» sahifasi bo'limlari",
                'verbose_name_plural': "«SPACE» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='VacanciesSection',
            fields=[
            ],
            options={
                'verbose_name': "«Vakansiyalar» sahifasi bo'limlari",
                'verbose_name_plural': "«Vakansiyalar» sahifasi bo'limlari",
                'ordering': ['order', 'key'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('value_ru', models.CharField(blank=True, max_length=120, verbose_name='qiymat (ru)')),
                ('value_uz', models.CharField(blank=True, max_length=120, verbose_name='qiymat (uz)')),
                ('value_en', models.CharField(blank=True, max_length=120, verbose_name='qiymat (en)')),
                ('label_ru', models.CharField(blank=True, max_length=200, verbose_name='izoh (ru)')),
                ('label_uz', models.CharField(blank=True, max_length=200, verbose_name='izoh (uz)')),
                ('label_en', models.CharField(blank=True, max_length=200, verbose_name='izoh (en)')),
                ('title_ru', models.TextField(blank=True, verbose_name='sarlavha (ru)')),
                ('title_uz', models.TextField(blank=True, verbose_name='sarlavha (uz)')),
                ('title_en', models.TextField(blank=True, verbose_name='sarlavha (en)')),
                ('text_ru', models.TextField(blank=True, verbose_name='matn (ru)')),
                ('text_uz', models.TextField(blank=True, verbose_name='matn (uz)')),
                ('text_en', models.TextField(blank=True, verbose_name='matn (en)')),
                ('note_ru', models.TextField(blank=True, verbose_name='natija/eslatma (ru)')),
                ('note_uz', models.TextField(blank=True, verbose_name='natija/eslatma (uz)')),
                ('note_en', models.TextField(blank=True, verbose_name='natija/eslatma (en)')),
                ('list_ru', models.TextField(blank=True, verbose_name="ro'yxat (ru)")),
                ('list_uz', models.TextField(blank=True, verbose_name="ro'yxat (uz)")),
                ('list_en', models.TextField(blank=True, verbose_name="ro'yxat (en)")),
                ('icon_name', models.CharField(blank=True, max_length=60, verbose_name='ikonka nomi')),
                ('icon', models.ImageField(blank=True, upload_to='sections/icons/', verbose_name='ikonka rasmi')),
                ('image', models.ImageField(blank=True, upload_to='sections/', verbose_name='rasm')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='havola')),
                ('is_published', models.BooleanField(default=True, verbose_name="ko'rsatilsin")),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pagesection', verbose_name="bo'lim")),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elementlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
