# Generated by Django 5.2.17 on 2026-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pagesection_aboutsection_commonsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='offer_url',
            field=models.URLField(blank=True, verbose_name='Ommaviy oferta'),
        ),
    ]
