# Generated by Django 5.2.6 on 2026-08-29 13:42

import apps.accounts.managers
import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[apps.accounts.validators.validate_uz_phone], verbose_name='telefon')),
                ('first_name', models.CharField(max_length=60, verbose_name='ism')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='familiya')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='avatar')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('admin', 'Administrator')], db_index=True, default='student', max_length=16, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodim')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="ro'yxatdan o'tgan sana")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RevokedRefreshToken',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token identifikatori')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='amal qilish muddati')),
                ('revoked_at', models.DateTimeField(auto_now_add=True, verbose_name='bekor qilingan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bekor qilingan token',
                'verbose_name_plural': 'Bekor qilingan tokenlar',
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
    ]
