# Generated by Django 5.2.6 on 2026-09-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='sessiya davri'),
        ),
    ]
