# Generated by Django 5.2.6 on 2026-09-04 07:53

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_session_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.core.uploads.avatar_upload_to, verbose_name='avatar'),
        ),
    ]
