# Generated by Django 5.2.6 on 2026-08-29 13:42

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=120, verbose_name='nomi (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=120, verbose_name='nomi (uz)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='nomi (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('icon', models.ImageField(blank=True, upload_to='directions/', verbose_name='ikonka')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=160, verbose_name='nomi (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=160, verbose_name='nomi (uz)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='nomi (en)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, verbose_name='qisqa izoh (ru)')),
                ('subtitle_uz', models.CharField(blank=True, max_length=300, verbose_name='qisqa izoh (uz)')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='qisqa izoh (en)')),
                ('description_ru', models.TextField(verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('card_image', models.ImageField(blank=True, upload_to='courses/', verbose_name='karta rasmi')),
                ('hero_image', models.ImageField(blank=True, upload_to='courses/', verbose_name='sahifa rasmi')),
                ('accent_color', models.CharField(default='#E94921', help_text='HEX формат: #E94921', max_length=7, verbose_name='aksent rangi')),
                ('age_from', models.PositiveSmallIntegerField(default=7, verbose_name='yosh (dan)')),
                ('age_to', models.PositiveSmallIntegerField(default=17, verbose_name='yosh (gacha)')),
                ('duration_months', models.PositiveSmallIntegerField(default=9, verbose_name='davomiyligi (oy)')),
                ('lessons_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='haftasiga darslar')),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField(default=90, verbose_name='dars davomiyligi (daqiqa)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="narx (oyiga, so'm)")),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='bosh sahifada')),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher', verbose_name="o'qituvchilar")),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.direction', verbose_name="yo'nalish")),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('title_ru', models.CharField(max_length=200, verbose_name='sarlavha (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('icon', models.ImageField(blank=True, upload_to='courses/features/', verbose_name='ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Kurs imkoniyati',
                'verbose_name_plural': 'Kurs imkoniyatlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseStage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('number', models.CharField(blank=True, max_length=4, verbose_name='raqam')),
                ('title_ru', models.CharField(max_length=200, verbose_name='bosqich nomi (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='bosqich nomi (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='bosqich nomi (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('image', models.ImageField(blank=True, upload_to='courses/stages/', verbose_name='rasm')),
                ('duration_months', models.PositiveSmallIntegerField(default=0, verbose_name='davomiyligi (oy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': "O'qish bosqichi",
                'verbose_name_plural': "O'qish bosqichlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_featured'], name='courses_cou_is_publ_bc1413_idx'),
        ),
    ]
