# Generated by Django 5.2.6 on 2026-09-03 14:30

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFaq',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('question_ru', models.CharField(max_length=255, verbose_name='savol (ru)')),
                ('question_uz', models.CharField(blank=True, max_length=255, verbose_name='savol (uz)')),
                ('question_en', models.CharField(blank=True, max_length=255, verbose_name='savol (en)')),
                ('answer_ru', models.TextField(verbose_name='javob (ru)')),
                ('answer_uz', models.TextField(blank=True, verbose_name='javob (uz)')),
                ('answer_en', models.TextField(blank=True, verbose_name='javob (en)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
