# Generated by Django 5.2.6 on 2026-09-04 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursefaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accent_color',
            field=models.CharField(default='#E94921', help_text='HEX формат: #E94921', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', message="Rang #RGB yoki #RRGGBB ko'rinishida bo'lishi kerak, masalan #E94921.")], verbose_name='aksent rangi'),
        ),
    ]
