# Generated by Django 5.2.6 on 2026-08-29 13:42

import apps.accounts.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('full_name', models.CharField(max_length=120, verbose_name='ism familiya')),
                ('phone', models.CharField(max_length=13, validators=[apps.accounts.validators.validate_uz_phone], verbose_name='telefon')),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bola yoshi')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='izoh')),
                ('source', models.CharField(choices=[('home', 'Bosh sahifa'), ('course', 'Kurs sahifasi'), ('courses', 'Kurslar sahifasi'), ('space', 'SPACE sahifasi'), ('quiz', 'Test natijasi'), ('contacts', 'Kontaktlar sahifasi'), ('popup', 'Popup forma')], default='home', max_length=16, verbose_name='manba')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Bog'lanildi"), ('enrolled', "Ro'yxatdan o'tdi"), ('rejected', 'Rad etildi')], db_index=True, default='new', max_length=16, verbose_name='holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin izohi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='branches.branch', verbose_name='filial')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx')],
            },
        ),
    ]
