# Generated by Django 5.2.6 on 2026-08-29 13:42

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('name_ru', models.CharField(max_length=160, verbose_name='nomi (ru)')),
                ('name_uz', models.CharField(blank=True, max_length=160, verbose_name='nomi (uz)')),
                ('name_en', models.CharField(blank=True, max_length=160, verbose_name='nomi (en)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='manzil (ru)')),
                ('address_uz', models.CharField(blank=True, max_length=255, verbose_name='manzil (uz)')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='manzil (en)')),
                ('landmark_ru', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (ru)")),
                ('landmark_uz', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (uz)")),
                ('landmark_en', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (en)")),
                ('working_hours', models.CharField(blank=True, max_length=160, verbose_name='ish vaqti')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='uzunlik')),
                ('map_url', models.URLField(blank=True, verbose_name='xaritadagi havola')),
                ('cover', models.ImageField(blank=True, upload_to='branches/', verbose_name='asosiy rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='bosh filial')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('image', models.ImageField(upload_to='branches/gallery/', verbose_name='rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'Filial rasmi',
                'verbose_name_plural': 'Filial rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
