# Generated by Django 5.2.17 on 2026-09-13 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('name_ru', models.CharField(max_length=160, verbose_name='nomi (ru)')),
                ('name_uz', models.CharField(blank=True, max_length=160, verbose_name='nomi (uz)')),
                ('name_en', models.CharField(blank=True, max_length=160, verbose_name='nomi (en)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='manzil (ru)')),
                ('address_uz', models.CharField(blank=True, max_length=255, verbose_name='manzil (uz)')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='manzil (en)')),
                ('landmark_ru', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (ru)")),
                ('landmark_uz', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (uz)")),
                ('landmark_en', models.CharField(blank=True, max_length=255, verbose_name="mo'ljal (en)")),
                ('working_hours_ru', models.CharField(blank=True, max_length=160, verbose_name='ish vaqti (ru)')),
                ('working_hours_uz', models.CharField(blank=True, max_length=160, verbose_name='ish vaqti (uz)')),
                ('working_hours_en', models.CharField(blank=True, max_length=160, verbose_name='ish vaqti (en)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('latitude', models.FloatField(blank=True, help_text="Xaritadagi nishon shu koordinatada turadi. Bo'sh qoldirsangiz — havoladan yoki manzildan avtomatik topiladi.", null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='kenglik (latitude)')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='uzunlik (longitude)')),
                ('map_url_yandex', models.URLField(blank=True, help_text='Masalan: https://yandex.uz/maps/?ll=69.240562,41.311081&z=17', verbose_name='Yandex Maps havolasi')),
                ('map_url_google', models.URLField(blank=True, help_text='Masalan: https://www.google.com/maps/@41.311081,69.240562,17z', verbose_name='Google Maps havolasi')),
                ('cover', models.ImageField(blank=True, upload_to='branches/', verbose_name='asosiy rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='bosh filial')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('image', models.ImageField(upload_to='branches/gallery/', verbose_name='rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='branches.branch', verbose_name='filial')),
            ],
            options={
                'verbose_name': 'Filial rasmi',
                'verbose_name_plural': 'Filial rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
