# Generated by Django 5.2.6 on 2026-09-04 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_split_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Xaritadagi nishon shu koordinatada turadi. Bo'sh qoldirsangiz — havoladan yoki manzildan avtomatik topiladi.", null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='kenglik (latitude)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='uzunlik (longitude)'),
        ),
    ]
