# Generated by Django 5.2.6 on 2026-08-29 13:42

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=80, verbose_name='nomi (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=80, verbose_name='nomi (uz)')),
                ('title_en', models.CharField(blank=True, max_length=80, verbose_name='nomi (en)')),
            ],
            options={
                'verbose_name': 'Yangilik turkumi',
                'verbose_name_plural': 'Yangilik turkumlari',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=200, verbose_name='sarlavha (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='sarlavha (en)')),
                ('excerpt_ru', models.CharField(max_length=400, verbose_name='qisqa matn (ru)')),
                ('excerpt_uz', models.CharField(blank=True, max_length=400, verbose_name='qisqa matn (uz)')),
                ('excerpt_en', models.CharField(blank=True, max_length=400, verbose_name='qisqa matn (en)')),
                ('body_ru', models.TextField(verbose_name='matn (ru)')),
                ('body_uz', models.TextField(blank=True, verbose_name='matn (uz)')),
                ('body_en', models.TextField(blank=True, verbose_name='matn (en)')),
                ('cover', models.ImageField(upload_to='news/', verbose_name='muqova')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='chop etilgan vaqt')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=3, verbose_name="o'qish vaqti (daq.)")),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rishlar")),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='bosh sahifada')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='turkum')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.news', verbose_name='yangilik')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
