# Generated by Django 5.2.17 on 2026-09-13 13:00

import apps.accounts.validators
import apps.quiz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('text_ru', models.CharField(max_length=300, verbose_name='savol (ru)')),
                ('text_uz', models.CharField(blank=True, max_length=300, verbose_name='savol (uz)')),
                ('text_en', models.CharField(blank=True, max_length=300, verbose_name='savol (en)')),
                ('image', models.ImageField(blank=True, upload_to='quiz/', verbose_name='rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='chop etilgan')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='tartib')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=200, verbose_name='nomi (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='nomi (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='nomi (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('questions_per_attempt', models.PositiveSmallIntegerField(default=20, help_text="Savollar bazasidan har safar shuncha savol tasodifiy tanlanadi. 0 — barcha savollar ko'rsatiladi.", verbose_name='bir urinishdagi savollar soni')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('title_ru', models.CharField(max_length=200, verbose_name='natija (ru)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='natija (uz)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='natija (en)')),
                ('description_ru', models.TextField(blank=True, verbose_name='tavsif (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='tavsif (uz)')),
                ('description_en', models.TextField(blank=True, verbose_name='tavsif (en)')),
                ('image', models.ImageField(blank=True, upload_to='quiz/outcomes/', verbose_name='rasm')),
                ('code', models.SlugField(help_text='Javoblardagi kod bilan bir xil', max_length=60, verbose_name='kod')),
                ('courses', models.ManyToManyField(blank=True, to='courses.course', verbose_name='tavsiya qilinadigan kurslar')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='quiz.quiz', verbose_name='test')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('text_ru', models.CharField(max_length=300, verbose_name='javob (ru)')),
                ('text_uz', models.CharField(blank=True, max_length=300, verbose_name='javob (uz)')),
                ('text_en', models.CharField(blank=True, max_length=300, verbose_name='javob (en)')),
                ('skill', models.CharField(blank=True, choices=[('logic', 'Логическое мышление'), ('math', 'Математическое мышление'), ('accuracy', 'Точность и порядок'), ('patience', 'Терпение'), ('creativity', 'Креативность'), ('visual', 'Визуальное восприятие'), ('communication', 'Коммуникабельность'), ('social', 'Социальная активность')], help_text="Shu javob qaysi ko'nikmani ko'rsatadi (natija tahlili uchun).", max_length=32, verbose_name="ko'nikma")),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.outcome', verbose_name='natija')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='test'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('public_token', models.CharField(db_index=True, default=apps.quiz.models.new_public_token, editable=False, max_length=64, unique=True, verbose_name='havola kaliti')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='ism familiya')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[apps.accounts.validators.validate_uz_phone], verbose_name='telefon')),
                ('answers', models.JSONField(default=dict, verbose_name='javoblar')),
                ('scores', models.JSONField(default=dict, verbose_name='natija ballari')),
                ('skills', models.JSONField(default=dict, verbose_name="ko'nikmalar foizi")),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='quiz.outcome', verbose_name='natija')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.quiz', verbose_name='test')),
            ],
            options={
                'verbose_name': "Test topshirig'i",
                'verbose_name_plural': 'Test topshiriqlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
