# Generated by Django 5.2.6 on 2026-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_per_attempt',
            field=models.PositiveSmallIntegerField(default=20, help_text="Savollar bazasidan har safar shuncha savol tasodifiy tanlanadi. 0 — barcha savollar ko'rsatiladi.", verbose_name='bir urinishdagi savollar soni'),
        ),
    ]
