# Generated by Django 5.2.6 on 2026-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_questions_per_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='skill',
            field=models.CharField(blank=True, choices=[('logic', 'Логическое мышление'), ('math', 'Математическое мышление'), ('accuracy', 'Точность и порядок'), ('patience', 'Терпение'), ('creativity', 'Креативность'), ('visual', 'Визуальное восприятие'), ('communication', 'Коммуникабельность'), ('social', 'Социальная активность')], help_text="Shu javob qaysi ko'nikmani ko'rsatadi (natija tahlili uchun).", max_length=32, verbose_name="ko'nikma"),
        ),
        migrations.AddField(
            model_name='submission',
            name='skills',
            field=models.JSONField(default=dict, verbose_name="ko'nikmalar foizi"),
        ),
    ]
